1. a.py and b.py at the same path
inside a.py
 import b

2. a.py and test/b.py, a.py and test at the same path
touch test/__init__.py
inside a.py
       import test.b

3. b.py at /test, not the same path with a.py
inside a.py
       import sys
       sys.path.append("/test")
       import b

https://zhuanlan.zhihu.com/p/451438246

weird issue

test/utils/config_parser.py
test/utils/__init__.py
test/pipeline/wonder.py
test/pipeline/__init__.py

in test/test.py
from pipeline.wonder import *
from utils.config_parser import *

tells utils is not a package

but 
from utils.config_parser import function_a
from pipeline.wonder import function_b
is ok

maybe import two local packages make namespaces conflict

